services:
  - type: web
    name: diabetic-retinopathy-app
    region: singapore
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=1 --timeout 120 --preload
    autoDeploy: true
