services:
  - type: web
    name: diabetic-retinopathy-app
    region: singapore
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
